# Change these first
owner: Ping-timeout # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: GitHub
    url: https://github.com
  - name: Busuu
    url: https://www.busuu.com
  - name: Ping_timeout 的 blog
    url: https://timeout.moe

status-website:
  cname: status.timeout.moe
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: Are you 💥?
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
